/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connection.forms;

import connection.clientes.Cliente;
import connection.mysql.ClienteDao.ClienteDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo lazzari
 */
public class Crud extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    ClienteDao clienteDao = new ClienteDao();
    /**
     * Creates new form Crud
     */
    public Crud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNomeCompleto = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldRg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crud Completo");
        getContentPane().setLayout(null);

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(420, 140, 63, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(330, 140, 80, 23);

        lblNomeCompleto.setText("Nome Completo:");
        getContentPane().add(lblNomeCompleto);
        lblNomeCompleto.setBounds(40, 10, 170, 40);

        lblIdade.setText("Idade:");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(40, 54, 80, 30);

        lblCpf.setText("CPF:");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(40, 94, 40, 30);

        lblRg.setText("RG:");
        getContentPane().add(lblRg);
        lblRg.setBounds(40, 134, 30, 30);
        getContentPane().add(jTextFieldNomeCompleto);
        jTextFieldNomeCompleto.setBounds(150, 20, 160, 20);
        getContentPane().add(jTextFieldIdade);
        jTextFieldIdade.setBounds(150, 60, 160, 20);
        getContentPane().add(jTextFieldCpf);
        jTextFieldCpf.setBounds(150, 100, 160, 20);
        getContentPane().add(jTextFieldRg);
        jTextFieldRg.setBounds(150, 140, 160, 20);

        jTableDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome Completo", "Idade", "CPF", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableDados);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 200, 480, 130);

        setSize(new java.awt.Dimension(517, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       salvarDados();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void salvarDados(){
         if (validaCamposObrigatorios()){
            JOptionPane.showMessageDialog(null, "preencha todos os campos antes de salvar os dados!");
        }else{
            try{
                cliente.setNomeCompleto(jTextFieldNomeCompleto.getText());
                cliente.setIdade(jTextFieldIdade.getText());
                cliente.setCpf(jTextFieldCpf.getText());
                cliente.setRg(jTextFieldRg.getText());
                clienteDao.criarRegitroNoBancoDeDados(cliente);
                limparCampos();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "erro ao salvar os dados: "+ e.toString());
            }
        }
    }
    private void limparCampos(){
        jTextFieldNomeCompleto.setText("");
        jTextFieldIdade.setText("");
        jTextFieldCpf.setText("");
        jTextFieldRg.setText("");
        jTextFieldNomeCompleto.requestFocus();
    }
    private boolean validaCamposObrigatorios(){
        return (jTextFieldNomeCompleto.getText().equals("")
                || jTextFieldIdade.getText().equals("")
                || jTextFieldCpf.getText().equals("")
                || jTextFieldRg.getText().equals("")
                );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDados;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldRg;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblRg;
    // End of variables declaration//GEN-END:variables
}
